# Github actions workflow name
name: CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  VSCode-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
         node-version: '18'
         cache: 'npm'
      - run: npm install
      # only test compile now, add unit test and e2e test in the future
      - run: npm run test-compile
